[package]
name = "data-onion"
version = "1.0.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Solution to Tom's Data Onion"
readme = "README.md"


[dependencies]
ascii85 = "0.2.1"
aes = "0.4.0"
block-modes = "0.4.0"
